/* This file autogenerated by src/common/Makefile */
char *default_plugin_path = "/users/kwangiit/slurmpp_v2/install/lib/slurm";
char *default_slurm_config_file = "/users/kwangiit/slurmpp_v2/install/etc/slurm.conf";
char *default_plugstack = "/users/kwangiit/slurmpp_v2/install/etc/plugstack.conf";
