#!/bin/bash -e

#function run {
    
    # n is number of controller
    # p is partition size
    # t is number of processing threads of a controller

    n=$1
    p=$2
    t=$3
    
    zht_base=/users/kwangiit/hpdc14/src/slurm-2.5.3/src/ZHT/src
    ctrl_base=/users/kwangiit/hpdc14/src/slurm-2.5.3/src/controller

    echo "running zht server"
    rm -rf host
    rm -rf zhtmemlist
    
    for i in `seq 1 $n`; do
        echo node-$i.distjoblaunch.usrc.kodiak.nx >> host
        echo node-$i.distjoblaunch.usrc.kodiak.nx 50000 >> zhtmemlist
    done

    cp zhtmemlist $zht_base

    echo "ld file"
    parallel-ssh -t 0 -A --hosts=host -O StrictHostKeyChecking=no -O UserKnownHostsFile=/dev/null 'sudo cp /users/kwangiit/hpdc14/config/ld.so.conf /etc/; sudo ldconfig'
    
    echo "start zht server"
    parallel-ssh -t 0 -o /tmp/ -p 250 -O StrictHostKeyChecking=no -O UserKnownHostsFile=/dev/null --hosts=host "$zht_base/zhtserver -z $zht_base/zht.conf -n $zht_base/zhtmemlist >& /tmp/zht_output &"
    
    sleep 5

    echo "running controllers"
    rm -rf ctrlnode
    for i in `seq 1 $n`; do
        echo node-$i >> ctrlnode #todo: node-1, node-2, not node-1.distjoblaunch.usrc.kodiak.nx, node-2.distjoblaunch.usrc.kodiak.nx ????
    done
    
    for i in `seq 1 $n`; do
	echo "$ctrl_base/controller /users/kwangiit/hpdc14/config/slurm.$i.$n.$p.conf $n /users/kwangiit/hpdc14/cmd/ctrlnode $p /users/kwangiit/hpdc14/workload/workload.$i.$n.$p $zht_base/zht.conf $zht_base/zhtmemlist $t $i"
	ssh node-$i.distjoblaunch.usrc.kodiak.nx -o 'UserKnownHostsFile /dev/null' -o 'strictHostKeyChecking no' "nohup $ctrl_base/controller /users/kwangiit/hpdc14/config/slurm.$i.$n.$p.conf $n /users/kwangiit/hpdc14/cmd/ctrlnode $p /users/kwangiit/hpdc14/workload/workload.$i.$n.$p $zht_base/zht.conf $zht_base/zhtmemlist $t $i >& /tmp/ctrl_output &"
    done
    
    sleep 5
    
    echo "running all the slurmds"
    #rm slurmdnode.txt
    
    #start=$(($n + 1))
    #end=$($n * $p) 
    
    for i in `seq 1 $n`; do
        rm -rf slurmdnode_${i}.txt
        k=$(($i-1))
        m=$(($k*$p))
        x=$(($m+$n))
        for j in `seq 1 $p`; do
            echo "node-$(($x+$j)).distjoblaunch.usrc.kodiak.nx >> slurmdnode_${i}.txt"
            echo node-$(($x+$j)).distjoblaunch.usrc.kodiak.nx >> slurmdnode_${i}.txt
        done
    done  

    echo "start to run slurmds"
    for i in `seq 1 $n`; do
        parallel-ssh -t 0 -o /tmp/ -p 250 -O StrictHostKeyChecking=no -O UserKnownHostsFile=/dev/null --hosts=slurmdnode_${i}.txt "/users/kwangiit/hpdc14/slurm/sbin/./slurmd -f /users/kwangiit/hpdc14/config/slurm.$i.$n.$p.conf &" 
    done

    echo "benchmark done here..."
    sleep 200
    
    echo "collect all the results of the controller"
    #cp /tmp/ctrl_output ~/hpdc14/output/ctrl_output_1
    
    for i in `seq 1 $n`; do
        scp -o 'StrictHostKeyChecking no' -o 'UserKnownHostsFile /dev/null' node-$i.distjoblaunch.usrc.kodiak.nx:/tmp/ctrl_output /users/kwangiit/hpdc14/output/ctrl_output_${i}
    done
    
    echo "kill all the controllers"
    
    parallel-ssh -t 0 -o /tmp/ -p 250 -O StrictHostKeyChecking=no -O UserKnownHostsFile=/dev/null --hosts=host "killall -9 controller &"
    
    sleep 5

    echo "kill all the zht servers"
    parallel-ssh -t 0 -o /tmp/ -p 250 -O StrictHostKeyChecking=no -O UserKnownHostsFile=/dev/null --hosts=host "killall -9 zhtserver &"
    
    echo "kill all the slurmds" 
    start=$(($n+1))
    all=$(($n*$p))
    end=$(($all+$n))
    rm -rf slurmdall.txt
    #bash killall.sh
    for i in `seq $start $end`; do
        echo node-$i.distjoblaunch.usrc.kodiak.nx >> slurmdall.txt
    done
    
    parallel-ssh -t 0 -o /tmp/ -p 250 -O StrictHostKeyChecking=no -O UserKnownHostsFile=/dev/null --hosts=slurmdall.txt "killall -9 slurmd &"

    echo "kill all the slurmstepds"
    parallel-ssh -t 0 -o /tmp/ -p 250 -O StrictHostKeyChecking=no -O UserKnownHostsFile=/dev/null --hosts=slurmdall.txt "killall -9 slurmstepd &"
#}
